server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mango?useUnicode=true&serverTimezone=GMT&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root