server:
  port: 8080
spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/mango?useUnicode=true&serverTimezone=GMT&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: root
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/springboot?useUnicode=true&serverTimezone=GMT&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: root