server:
  port:8080
#  port: 443
#  ssl:
#    key-store: classpath:2831966_www.ycyoes.com.pfx
#    enable: true
#    key-store-password: 5HxPU0CW
#    key-store-type: PKCS12
spring:
  datasource:
    druid:
      master:
        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: oracle.jdbc.driver.OracleDriver
#        url: jdbc:oracle:thin:@localhost:1521:xxxqzz
#        username: xxxqzz
#        password: 123456
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/mango?useUnicode=true&serverTimezone=GMT&autoReconnect=true&characterEncoding=utf-8
#        username: root
#        password: root
#        connectionProperties: config.decrypt=true
        filters: com.turing.springbootintegrate.filters.SecurityConfigFilter,stat,wall,log4j
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@172.28.7.19:15227:xe
        username: cigproxy
        password: Htzhcig_5873
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&serverTimezone=GMT&autoReconnect=true&characterEncoding=utf-8
        username: root
        password: root
        connectionProperties: config.decrypt=true
        filters: com.turing.springbootintegrate.filters.SecurityConfigFilter,stat,wall,log4j
      connectionProperties: config.decrypt=true
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 600000
      min-evictable-idle-time-millis: 350000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**